language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
script:
  # python tests
  - PYTHONPATH=src python -m coverage run --branch --source=src -m unittest discover -s tests -v
after_success:
  # coverage reports
  - python -m coverage report -m
